Add version constraints for py26
Some transitive dependencies no longer support Python 2.6.  Add a pip
constraints file to ensure appropriate versions are installed.

idna-2.8 fails to install due to `setup.py` requirement:
`idna requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 2.6.9`
Require <2.8.

pycparser-2.19 fails to install on Python 2.6 due to
`from subprocess import check_output` in `pycparser/__init__.py` which
causes `ImportError: cannot import name check_output`.  Require <2.19.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>