If region is in fact specified, i think it should be a string (that seems to be true for most other boto connections, and is much cleaner in any case) -- the lookup dict (to endpoint) exists, but currently the endpoint lookup doesnt work, so this should fix that so that str region specified works.
---
Original error:
  File "/xxxx/ec2/elb/__init__.py", line 96, in __init__
    self.region.endpoint, debug,
  AttributeError: 'str' object has no attribute 'endpoint'