Fix OpsWorks helpers
Previously calling them would cause the exception:

  File “…/boto/opsworks/layer1.py", line 99, in __init__
    super(OpsWorksConnection, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'region'

This is now fixed and unit tested.