Fix AttributeError: 'Provider' object has no attribute 'encode'
2.32.0 introduces this error - several updates to encode
self._provider.secret_key, but one too many that attempt to encode
self._provider itself.